version: '3.3'
services:
  reverse-proxy:
    image: nginx:latest
    restart: always
    deploy:
      replicas: 1
    ports:
      - "80:80"
    volumes:
      - nginx_config:/etc/nginx
#      - static_content_game:/etc/nginx/html
    networks:
      pg_network:
          aliases:
            - proxy_node
    container_name: reverse_proxy


  landing:
    image: expovin/pglanding:latest
    restart: always
    deploy:
      replicas: 1
#    ports:
#      - "3010:3000"
    networks:
      pg_network:
          aliases:
            - landing_node
    container_name: pg_landing

  game:
    image: expovin/presalesgame:latest
    restart: always
    deploy:
      replicas: 1
#    ports:
#      - "3020:3000"
#    volumes:
#      - static_content_game:/usr/src/app/dist
    networks:
      pg_network:
          aliases:
            - game_node   
    container_name: pg_game

#  qix:
#    image: qlikcore/engine:12.260.0
#    restart: always
#    command: -S AcceptEULA=yes
#    environment:
#       AcceptEULA: 'yes'
#    deploy:
#      replicas: 1
#    ports:
#      - "19076:9076"
#    volumes:
#      - ./data:/data
#    networks:      
#      pg_network:
#          aliases:
#            - qix_node    
#    container_name: pg_qix

  mysql:
    image: mysql/mysql-server:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'super$ecret' # TODO: Change this
      MYSQL_USER: 'pguser'
      MYSQL_PASSWORD: 'pgpasswd'    
      MYSQL_DATABASE: 'pg_data'
    deploy:
      replicas: 1
    ports:
      - "3306:3306"
    volumes:
      - game_data:/var/lib/mysql     
    networks:
      pg_network:
          aliases:
            - db_node     
    container_name: pg_db 

volumes:
  nginx_config:
  static_content_game:
  game_data:

networks:
  pg_network:
    driver: "overlay"
