version: '3.3'
services:
  reverse-proxy:
    image: nginx:latest
    deploy:
      replicas: 1
    ports:
      - "80:80"
    volumes:
      - nginx_config:/etc/nginx
      - static_content_game:/etc/nginx/html
    networks:
      pg_network:
          aliases:
            - proxy_node
    container_name: reverse_proxy


  landing:
    image: expovin/pglanding:0.8
    deploy:
      replicas: 1
    ports:
      - "3010:3000"
    networks:
      pg_network:
          aliases:
            - landing_node
    container_name: pg_landing

  game:
    image: expovin/presalesgame:0.82
    deploy:
      replicas: 1
    ports:
      - "3020:3000"
    volumes:
      - static_content_game:/usr/src/app/dist
    networks:
      pg_network:
          aliases:
            - game_node   
    container_name: pg_game

#  qix:
#    image: qlikcore/engine:12.260.0
#    command: -S AcceptEULA=yes
#    deploy:
#      replicas: 1
#    ports:
#      - "19076:9076"
#    volumes:
#      - ./data:/data
#    networks:      
#      pg_network:
#          aliases:
#            - qix_node    
#    container_name: pg_qix



volumes:
  nginx_config:
  static_content_game:

networks:
  pg_network:
    driver: "overlay"
